version: '3'
services:
  my-app:
    container_name: mynode-app02
    image: housseinyn/nodejs-app_my-app01
    restart: always
    build: .
    ports:
     - 3000:3000 
  mongo:
    image: mongo:4.4.0
    restart: always
    volumes:
      - mongo-db:/data/db
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongo:27017/
volumes:
  mongo-db:



