---
- name: "Build Image and run container with ansible playbook"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop nodjs-container
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm nodjs-container
    ignore_errors: yes
# Make sure to change the image name with your personal dockerhub account and reposiroty   
  - name: remove used image
    command: docker rmi housseinyn/nodejs-app_my-app01
    ignore_errors: yes
# Make sure to change the image name with your personal dockerhub account and reposiroty 
  - name: build docker image from dockerfile
    command: docker build -t housseinyn/nodejs-app_my-app01 .  
# Make sure to change the image name with your personal dockerhub account and reposiroty 
  - name: push image to dockerhub
    command: docker push housseinyn/nodejs-app_my-app01



  